### PR TITLE
Java11

### PR DESCRIPTION
**Pull request by erikkemperman**
Ref. https://github.com/powertac/powertac-server/issues/1023

### CODE REVIEW

**Comment by erikkemperman** [comment]
Note, the "PR" Travis build fails because it requires the java11 branch of powertac-core to be merged into master first. The "Push" build succeeds, because it is clever enough to get the same-name branch of powertac-core.

**Comment by jecollins** [comment]
As I understand it, this PR will merge the java11 branch back to master. I finally have time to look at it, I'll try to get this done in a couple days at most.

**Comment by jecollins** [comment]
I've checked out the java11 branch for powertac-core, powertac-server, and sample broker. It all builds, but sample-broker exits immediately when I try to run a game. It appears that sample-broker is having problems with XStream:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/home/jcollins/.m2/repository/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by erikkemperman** [comment]
I've been able to run the sample broker succesfully (after installing everything else on the proper branch, obviously).

The warning you mention is something I've mentioned [here](https://github.com/powertac/powertac-server/issues/1023#issuecomment-522041529) but didn't seem to me to be an actual error.

Is there more output?

**Comment by jecollins** [comment]
The broker received a sim-end message at the end of the bootstrap data, so it just quit as expected.

**Comment by erikkemperman** [comment]
Not sure if it matters, but was the bootstrap generated on java11?

**Comment by jecollins** [comment]
Also, the entire boot configuration, including all the customer usage data, weather reports, and market data, are sent to the broker twice before the sim-end is sent. We need to see if this is happening in the released version.

**Comment by jecollins** [comment]
The release version running under Java 8 does NOT send two copies of the server config and bootstrap data to the broker at startup. This is a serious anomaly.

**Comment by erikkemperman** [comment]
Did you see if this happens on the master branch? Did you find an easy way to test this? If so we can bissect to find which commit introduced this anomaly.

**Comment by jecollins** [comment]
Updated and freshly installed master branch, running under Java 8, does not exhibit this behavior.

**Comment by jecollins** [comment]
I added a test for powertac-core/.../StateLogging to do essentially what's in RandomSeedRepoTest. The test passes when run inside my IDE (I did a fresh download and re-installed, it's all good now). But if fails when maven does the build in the same way the RandomSeedRepo test fails when building powertac-server under maven.

**Comment by jecollins** [comment]
You are correct. I was misled by a [different problem, related to the eclipse-maven integration](https://stackoverflow.com/questions/6352208/how-to-solve-plugin-execution-not-covered-by-lifecycle-configuration-for-sprin). I have re-built and re-installed, and I don't see the multiple-initialization behavior. It's not clear that anything I've done would have affected that.

**Comment by erikkemperman** [comment]
So... Now we're not sure if things are all right? If you let me know how specifically you were testing for the multiple boots being sent to brokers, I can try to re-install everything a couple of times and see what happens.

**Comment by jecollins** [comment]
After getting it to work correctly on my system, I have not seen the multiple-init problem. I think I'm going to finish up the PR and tackle other issues as they arise, including the access warnings.

**Comment by erikkemperman** [comment]
I think I've addressed all current security alerts now; I've updated the two open PRs. One might not be automatically detected by Github as being fixed -- I've had to resolve it manually as mentioned in the description:

C.f.
https://github.com/jhipster/generator-jhipster/security/advisories/GHSA-mwp6-j9wf-968c
https://www.jhipster.tech/2019/09/13/jhipster-release-6.3.0.html

Which I think I resolved here:
https://github.com/powertac/powertac-server/pull/1025/commits/2573c069fa398d4613515162288b667ea3e6f1d4

So if that's the case I believe we can safely dismiss that alert.

**Pull request merged**
