### PR TITLE
Single repo

### PR DESCRIPTION
**Pull request by erikkemperman**
Like powertac-core, please clone this fresh: `git clone https://github.com/powertac/powertac-server -b single_repo`

### CODE REVIEW

**Comment by jecollins** [comment]
The dependencies on powertac-core are to 1.4.1, not 1.4.2-SNAPSHOT. That should be fixed.

**Comment by erikkemperman** [comment]
You mean powertac-parent, here:
https://github.com/powertac/powertac-server/blob/single_repo/pom.xml#L51
?

Indeed that will not be done by the release plugin. I'll tack it onto this branch shortly.

**Comment by erikkemperman** [comment]
Done.

**Comment by erikkemperman** [comment]
Thanks for review and merge John!

**Pull request merged**
