### PR TITLE
Fix remember-me cookie handling (missed part of jhipster upgrade)

### PR DESCRIPTION
**Pull request by erikkemperman**
@jecollins  Hopefully this fixes the 500 error due to mishandling of remember-me tokens (had missed this because I always test in incognito mode to defeat cache, will try in normal mode as well from now on!)

### CODE REVIEW

**Comment by jecollins** [comment]
I pulled down the fix-remember-me branch, merged, did a local clean install. When I run it with -Pweb2, I still get the 500 error. So I killed it, removed the files/system dir, and restarted it. Still get a 500 error. Here's the trace from visualizer.log:
```
2018-11-08 10:53:58.199 ERROR 3781 --- [nio-8080-exec-1]o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

org.hibernate.LazyInitializationException: could not initialize proxy [org.powertac.visualizer.domain.PersistentToken#W7MZxdN8R4eK7Rs2YudT] - no Session
        at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:169) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
        at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:309) ~[hibernate-core-5.3.7.Final.jar!/:5.3.7.Final]
```

**Comment by jecollins** [comment]
Removing the cookies again fixes the problem. I guess we'll have to tell folks to remove cookies before the new version will run?

**Comment by jecollins** [comment]
I can shut down and restart the server without having to remove files or cookies a second time.

**Comment by erikkemperman** [comment]
Yes, I believe that happens once, if the browser has a previous session (cookie). I added a note in the server-distribution readme.

**Pull request merged**
