### PR TITLE
Viz2 wholesale

### PR DESCRIPTION
**Pull request by erikkemperman**
John,

I've added some wholesale market plots -- could you please check if this makes sense, at least superficially? You should see two "pills" below the first graph to switch between retail and wholesale. 

Additionally I have improved (I hope) the mouseover tooltip of the charts a bit, it now aligns the values and sorts them (in the same order as the plots) depending on the x-coordinate :-)

Meanwhile, I will add some weather plots tomorrow.

Thanks!

### CODE REVIEW

**Comment by jecollins** [comment]
I guess these updates are not currently deployed in the trial? I've pulled down your branch and testing locally.

**Comment by erikkemperman** [comment]
That's right, I would very much appreciate if you would check if the logic, especially in `.../domain/WholesaleKPIHolder.java` makes sense!

**Comment by erikkemperman** [comment]
Hi John,

I fixed an error and reduced some bandwidth footprint (more compact JSON serialization) which otherwise became a bit problematic with the added wholesale data now being sent to the frontend.

**Comment by erikkemperman** [comment]
I've further reduced the JSON by avoiding sending empty customer records. This was especially annoying as we don't even plot any of this data yet!

**Comment by jecollins** [comment]
This looks better, no zero values for per-timeslot money and energy for most brokers. But the prices seem way high. I don't like sending NAN for cases where a broker sold more than it bought. Some brokers pursue a strategy of just buying retail energy (solar panels) and selling it in the wholesale market. I also don't understand the way you are computing the price, and I suspect it's not correct. Finally, I'm not sure why you are using a bar chart for prices, seems like a line chart would be easier to read.

**Comment by erikkemperman** [comment]
Sorry, I just replied to your email instead of on GitHub... I'll copy/paste here for record keeping purposes:

Hi John,

The prices are more or less in line with the individual MarketTransaction messages I saw, but I also noticed there's a lot of difference between brokers. However the computation is the same for all of them, so they should be all right or all wrong...

I'm not sending NaN in those cases, I don't think: notice that the "total" variable is absolute, so effectively I'm just avoiding dividing by zero (and getting Infinity). I think it makes sense to send NaN because it causes the graph framework to "skip" that timeslot for the broker, in stead of sending say 0 which would be misleading (since zero is a valid price, as far as I know). Does that sound reasonable?

This is also why I thought a bar chart would be better, the framework doesn't handle gaps well with line charts. (If you like you can try to replace "column" with "line" here, to see what I mean:

https://github.com/powertac/powertac-server/pull/940/files#diff-4d47e53cd720eaa1255d59b6e26a4281R33

The conflicts are probably due to my amending an earlier commit, instead of making a new additive one. As long as things are not merged into master I prefer it that way, because you end up with clean commits in master eventually.

The remedy, if this is in fact the problem:

git checkout master
git branch -D <my-branch>
git checkout <my-branch>

Hope this helps!

**Comment by jecollins** [comment]
I wonder -- if wholesale energy is negative for a ts (broker sold more than bought), should the price also be negative? On the other hand, the convention throughout the system is that prices and quantities are from the viewpoint of the "target" entity, which in this case is a broker. So purchased energy should be positive, and the associated cost is negative. Why are we making it positive in these graphs?

**Comment by jecollins** [comment]
Another thought: Some brokers trade in the wholesale market when they have no customers, buying energy when they think prices are low and selling it when they think it's high, essentially doing arbitrage across the 24 timeslots in the forward market. Would we be better off separating purchases from sales and showing both prices? In this case the divide-by-zero problem goes away -- the correct value would in fact be zero.

**Comment by erikkemperman** [comment]
Yes, I am merging buy/sell here -- but accounting for the signs, of course. The prices in the graph are just the aggregate "money per MWh" for all market transactions in a timeslot, per broker, so I think it makes sense those turn out (mostly) positive?

**Comment by jecollins** [comment]
But you are not really merging buy/sell. You are computing essentially abs(buy) + abs(sell) rather than buy + sell, which (because the buy quantity is + and sell qty is -). You should leave the total computation out of the if(m < 0) conditional, and just add up the buy and sell quantities, giving the net quantity, which might be either positive or negative. The m*p calculation either needs to be inside the conditional, or better perhaps to compute money+=abs(m)*p.

**Comment by erikkemperman** [comment]
I think I am computing buy + sell to compute the deltas in energy and money, but use the absolute values to compute mean price (across buys and sells). Or that's what I wanted to do anyway :-)

Unfortunately I'm going to have to sign off now... Holiday preparations. You have a much better grasp on this material than I do, so if you like please change as you see fit!

**Comment by jecollins** [comment]
I've been running some experiments. I created a logtool that replicates the qty/price calculations, and we get some very strange results when brokers both buy and sell energy in the same timeslot. That's because if a broker buys 9 mwh at -35, then sells back 8.9 mwh at 41, we have mwh=0.1, money=49.9, and the final price is 499. This makes no sense; the market never cleared anywhere near that; instead, the broker made a modest profit on a small net quantity. Of course, if the broker is doing arbitrage without any customers, it's easy to imagine the net quantity being zero, and the price is meaningless the way we are currently computing it. I think we need to track purchase price and selling price separately. They would (normally) be on opposite sides of the x-axis. It would be nice to show quantities in the same plot. That's up to four values per broker in each timeslot. Any ideas?

**Comment by erikkemperman** [comment]
Hi John,

Thanks again for reviewing this!

I'm typing this on my phone in the train to the airport, so apologies I can't actually run this at the moment... But are you sure you've reproduced the same calculation in your analyzer?

Here's what I intended to happen, plugging in your example transactions by hand into my arithmetic in `WholesaleKPIHOlder`:

Before first transaction:
```java
total = 0;  // sum of abs(energy) changing hands
money = 0;  // delta in broker cash
mwh = 0;    // delta in broker energy
price = 0;  // running sum of abs(energy * price)
```

First transaction (buying), `m = +9` and `p = -35`:
```java
total += +9;       // total now at +9
money += +9 * -35; // money now at -315
mwh += +9;         // mwh now at +9
price -= +9 * -35; // price now at +315
```

Second transaction (selling), `m = -8.9` and  `p = +41`:
```java
total -= -8.9;       // total now at +17.9
money -= -8.9 * +41; // money now at +49.9
mwh += -8.9;         // mwh now at +0.1
price -= -8.9 * +41; // price now at +679.9
```

After the last transaction the broker's cash delta is `49.9` (the modest profit) and the energy delta is `+0.1` (the surplus bought - sold) which strikes me as correct. Then I divide the sum of abs(energy * price) by the sum of abs(energy) to get the mean price per MWh over these two transactions:
```java
price /= 17.9; // price now at 37.983...
```

So, I don't think I am computing mean prices by dividing the delta cash by delta energy, `49.9 / 0.1`, which I think might be how you ended up with `499`. Instead this scenario should leave the price plotted for this broker in this timeslot with just these two MarketTransactions at `37.983` which seems reasonable.

The "regular" transactions, with `m` and `p` of opposite signs, are handled correctly, it seems to me... Possibly there could be cases with same-sign transactions that defeat my procedure? Or what am I missing here?

It still might make sense to separately tally buys and sells, of course. But that would require a bunch of changes in the front-end also (mostly in `src/main/webapp/app/graphs/graphs.html` and `src/main/webapp/app/services/state.service.js`) and unfortunately I am not going to be able to implement that whilst on holiday, and thus not in time for the finals...

Having said all that, I think having quantities and prices in the same plot might be confusing, especially when splitting buys and sells (that would leave up to 32 series in a single graph for an 8-broker game).

**Comment by jecollins** [comment]
You are correct -- my approach using net quantity and money does not produce a sensible result for price. But I was seeing what looked like nonsense in some of the plots from the tournament as well, so either that was not your latest code, or there's still a problem lurking. Also, I'm not sure this single number is very informative. Maybe we need two plots, one showing energy purchases and one showing energy sales? Also, quantities matter, and they can range over at least 4 orders of magnitude.

**Comment by erikkemperman** [comment]
We could check the logs for market transactions in time slots that show unreasonable prices and plug those into the procedure?

A separate plot showing net volumes, per broker per timeslot, wouldn't be too difficult I think. Per transaction is probably not going to work, too much information to make sense of it from a single graph?

Very sorry I can't be of much help, I'm in Ravenna -- the house we're in is gorgeous but the wifi is flaky.

**Comment by jecollins** [comment]
I fixed the calculation, but there remains a problem with using the bar-chart style. When the display gets dense, bars are consolidated, and their quantities added together. So depending on how much consolidation happens, the values shown by the bar chart appear to be a small integer multiple of the correct values. It looks like the first consolidation (doubling) happens in about 7 days on my display. Details probably depend on display width.

Here's the corrected calculation:
```
                    if (m < 0) {
                        // Sold energy
                        total -= m;
                        money -= m * p;
                    } else {
                        // Bought energy
                        total += m;
                        money -= m * p;
                    }
                    mwh += m;
                    //price -= m * p;
                }
                if (total > 0) {
                    price = money / total;
                    empty = false;
```
Remember that price and quantity are (almost) always of opposite signs.

**Comment by erikkemperman** [comment]
Thanks John!

So if I read this correctly you're now using the `money` variable to calculate the price at the end... But since the product of price and quantity per transaction is usually negative, you're now _increasing_ money for a broker when it's buying energy?

I meant for that metric to be a net delta so I figured it should be negative when buying -- and that's why I had a `price` variable to tally the absolute amounts...

I haven't noticed the graph framework coalescing series together but that might explain some of the spikes we saw? Probably it has a configuration option to disable that or modify the threshold.

Unfortunately I can't look that up at the moment, maybe you could look for the "highstock" documentation for bar plots? If you find the appropriate config key you could add it to the place I linked earlier in this thread (near where "column" currently defines the chart type).

Hope this helps, I'll be traveling again today (Ravenna to Bologna) but will try to check in again this evening.

**Comment by jecollins** [comment]
The purpose of this calculation is as you said, to get the average per-MWh price of all market transactions, both buy and sell transactions. So we gather the total amount traded (positive for sell, neg for buy) and the total money (p*m is always negative on the wholesale market, but not necessarily in the balancing market). So we are collecting sum(abs(mwh)) and sum(abs(money)) and taking the ratio. Seems simple, and seems correct. Your approach seemed unnecessarily complicated, and was giving much bigger numbers for price. Often the computed price was higher than the price on any individual transaction.

**Comment by erikkemperman** [comment]
Sorry, I'm probably missing something subtle...

It seems to me your price calculation is the same as mine: you're subtracting `m*p` -- for both buying and selling, it could be outside of the if/else -- from `money`, exactly like I was doing from `price`, to then divide that by the same `total` as I was doing, right?

https://github.com/powertac/powertac-server/pull/940/files#diff-df77366d81268701f00ab81536180372R75

But I'm not sure what the `money` metric now means in the graphs, it always increases for both buys and sells. I would expect the `energy` and `money` graphs to be inversely proportional (the local ratios being prices)?

**Comment by jecollins** [comment]
OK, I discovered the display scaling problem after I changed the code, and I was not paying attention to the "money" plot. I went back to your code and narrowed the date range to just under 7 days, and the numbers are correct. So your code is fine, it's the plotting that's wrong. We could either find a way to make line plots work, or find a way to prevent the bar plots from scaling up. I've looked through the Highcharts docs and several StackOverflow discussions, and have not found a solution. I think in its current state we cannot use it -- it will cause confusion.

**Comment by erikkemperman** [comment]
You could try if a line chart would be better by removing `type: column` here:
https://github.com/powertac/powertac-server/pull/940/files#diff-4d47e53cd720eaa1255d59b6e26a4281R33

I think this coalescing behavior might be "stacking" as described here:
http://api.highcharts.com/highcharts/plotOptions.column.stacking
But I'm not sure because I don't think I set that option and I would expect the default to be not to stack.

If that's the case you could try disabling it by setting it to `null` either in the specific plot options (alongside the `type` option I linked above) or for all graphs here:
https://github.com/powertac/powertac-server/pull/940/files#diff-fe61710d4f36984e86f76bbd9b6a8f0aR132

I apologize profusely for not noticing this coalescing thing myself and dropping this with you -- whilst I enjoy a holiday... My calculation seemed to make sense in individual cases I tracked, and so I figured the spikes I saw were really reflecting the data produced in the game!

**Comment by erikkemperman** [comment]
Sorry (again) -- I'm on a phone and had my fat finger on the wrong button. Reopening.

**Comment by jecollins** [comment]
I tried the line graph, and it looks fine. So I tried it on a couple of games from the 2016 final [here's the first one](http://ts.powertac.org/log_archive/finals_2016_06/finals_2016_06_1.tar.gz). It appears to plot wholesale data for roughly two days, and then flatlines. The overview and retail plots look fine.

**Comment by erikkemperman** [comment]
Oops, I expected that to be a screenshot -- instead I downloaded a good chunk of tarball before I noticed. Thankfully I was on wifi and not roaming :-)

So I can't run the visualizer with that game and see what you mean... It would be interesting to see if, when running in "-Pdebug,research" profile, the web console in the browser still shows wholesale data coming in when the graphs flatline.

Perhaps the NaN values are confusing the graph framework? Does it help if we send zero prices instead, when there are no transactions for a broker in a timeslot?

**Comment by erikkemperman** [comment]
Also, does it do that for all games? If I remember correctly some brokers had connectivity issues and were not doing any transactions during some games.

**Comment by erikkemperman** [comment]
John, I believe I've fixed the re-replaying errors (flatlining graphs when starting a replay for a second time). These errors were actually in logtool-core, see the last couple of commits with that prefix.

Basically, the logtool-core was failing to recycle repos in between games (of course it was originally only ever expected to play a single game). Thus many messages from state logs caused conflicts because the given IDs were already present in the repos.

Additionally we were re-registering listeners over and over and this was severely degrading performance, so I am now doing that just once in a `@PostConstruct` method.

I should have perhaps made a separate PR with the last couple of commits but wanted to demonstrate that the wholesale plots now no longer flatline with these in here, so I decided to include them.

Hope that makes sense.

**Comment by jecollins** [comment]
Good catch. That module was not designed to operate in a multi-session environment, but it's been around for a while and it did not occur to me to look into this when we incorporated it into the server. Obviously, anything running in the server environment should be capable of multi-session operation. The way all the other services do this is to implement the InitializationService interface. That way, the CompetitionControlService invokes the initialize() method after setting up the environment for a new session. Ideally, that's what we would do for logtool-core, rather than using the PostConstruct annotation, because it will allow CompetitionControlService to incorporate it into the server's session setup sequence.

**Comment by erikkemperman** [comment]
That makes sense -- but the way the visualizer currently interacts with logtool-core does not involve the server at all. I guess that can be remedied, by equipping the `CompetionControlService` (and/or `CompetitionSetupService`?) with replay capability in addition to starting boot/sim sessions.

But that would be a pretty significant change... And other than initializing the peripheral components the server would not actually participate in replay, it seems to me.

Would it be all right to revisit this later, separately from this PR, or would you prefer I attempt to bolt in on here?

**Comment by jecollins** [comment]
Ah - there are two kinds of sessions. I guess the viz is the only component that participates in both. Or does it? In any case, as you say, viz sessions are not under the control of CCS, and AFAIK, CCS does not use logtool-core itself at all. So I guess my suggestion that logtool-core be Initializable really makes no sense. On the other hand, logtool-core DOES make use of server resources, like repos, and needs to recycle them. I wonder if there's a way to consolidate what's common to CCS sessions and viz sessions without making logtool-core dependent on server-main. Whatever it is would have to be somewhere in common, I suppose. If it's just the repos, they are all in one package, and we could perhaps add a small controller to that package. Before we do that though, let me take a closer look at what you did.

**Comment by erikkemperman** [comment]
It also just occurred to me that it feels odd for things like the logtool examples to depend on server-main.

But I think that it's just the repos, from common, and so if we wanted I believe we could lift some parts of server main (at least the bits calling the `recycle` methods and possibly some initialization callbacks) from server-main to common -- and then call that from logtool-core as well?

Anyway, yes, I for one would prefer to attack that particular problem separately. Curious what you think of the split (buy/sell) price plots. Do you think the aggregate price plot should stay? Would it be better to split the MWh plots as well?

**Comment by erikkemperman** [comment]
John, just touching base to avoid us waiting on one another -- have you had a chance to look at those split (buy/sell) price plots?

**Comment by jecollins** [comment]
Hello, Erik - I finally got it set up and looked at a couple of games. I really like it. The selling-price plot just leaves gaps when brokers are not selling -- that seems quite appropriate. Do you have any objection to merging it? I think we're ready to move on to other issues.

**Comment by erikkemperman** [comment]
Thanks for taking a look! Do you think the MWh plots should be split as well, and does it make sense to keep the aggregate price plot in there?

Before merging, let me squash the "Temporary" commits together and force-push it to this PR, so as not to pollute master.

**Comment by erikkemperman** [comment]
All right, I've pushed a cleaner history of pretty much the same thing. Two more little things, mostly suggested by Govert:
- I'm now also showing the current timeslot and corresponding simulation time.
- I've included an overall legend (symbol and color, mutually verified by Govert to be distinguishable by the colour-blind) for each of the brokers. These are clickable so you can hide/show the lines per broker. This helps resolving some visibility issues when one or two of the brokers veer off the others and because of their effect on the Y-axis scale it became hard to separate the other broker's lines.

From my point of view, if you like these last two additions as well, this PR is now ready to be merged.

Thanks again for your review (and patience).

**Comment by jecollins** [comment]
I like the legend and the ability to turn individual brokers on/off. I think I'll merge on github; I don't trust my current environment, because I keep getting merges when I try to pull down the PR. Also, I tried multiple times to load game 65 from zenodo and the viz just hangs. Without logs, it's impossible to know what's happening.

**Comment by erikkemperman** [comment]
Yeah, that's why I did the incremental commits instead of amending -- it's a bit of a hassle to pull down branches if their history changed.

What does help avoiding trouble, though, is to use `git fetch` and `rebase` instead of `pull`. Then you'll have the option of aborting at least, when conflicts arise.

**Comment by erikkemperman** [comment]
I'll look into game 65 tomorrow!

**Comment by erikkemperman** [comment]
For what it's worth, replaying game 65 works fine here:
screenshot from 2017-06-29 09-23-51

**Comment by jecollins** [comment]
Works for me now as well. I have no idea what happened yesterday. However, it's merged and deployed. Should we make an announcement, or just let folks discover it?

**Comment by erikkemperman** [comment]
Well, I was trying to get a few little other things in there -- mainly to counteract somewhat the slightly crappy performance we're now seeing with all those extra plots... But that is turning out to be trickier than expected and I might need to take it up with the developers behind Highcharts' and/or its Angular plugin.

On the one hand I would prefer to get that done before too many people try it and are possibly a bit disappointed at degraded performance, on the other hand it would likely take another couple of days, best case, to get it resolved adequately.

**Comment by jecollins** [comment]
Sounds good. It seems to work now, but if you can improve performance with a reasonable amount of effort, now is probably the best time to do it while it's still fresh in your mind.

**Pull request merged**
